name: Publish PR Build

on:
  workflow_run:
    workflows: [Verify]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    steps:
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
      - id: get-xpi
        name: Get xpi artifact
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            const xpiArtifact = allArtifacts.data.artifacts.find((artifact) => {
              return artifact.name == "xpi"
            });
            return xpiArtifact.archive_download_url
      - name: Comment PR build
        uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ github.event.workflow_run.pull_requests[0].number }}
          message: |
            **✅ Successful build again**

            ${{ steps.get-xpi.outputs.result }}
