name: Publish PR Build

on:
  workflow_run:
    workflows: [Verify]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
