name: Release

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v4
  publish-artifacts:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: "npm"
          registry-url: "https://npm.pkg.github.com"
      # Skip post-install scripts here, as a malicious script could steal NODE_AUTH_TOKEN.
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build
      - id: publish-xpi
        name: Publish xpi
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: xpi/*.xpi
          fail_on_unmatched_files: true
      - name: Generate update manifest
        run: npm run generateUpdateManifest -- ${{ fromJSON(steps.publish-xpi.outputs.assets)[0].browser_download_url }}
      - name: Publish update manifest
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: gen/update*
          fail_on_unmatched_files: true
      - name: Publish release
        run: gh release edit ${{ needs.release-please.outputs.tag_name }} --draft=false
